CREATE TABLE IF NOT EXISTS `BOARD` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`UPDATE_ID` BIGINT NULL DEFAULT NULL,
	`IS_DELETE` TINYINT NULL DEFAULT NULL,
	`IS_HIDDEN` TINYINT NULL DEFAULT NULL,
	`TITLE` VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `BOARD_ARTICLE` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`UPDATE_ID` BIGINT NULL DEFAULT NULL,
	`IS_DELETE` TINYINT NULL DEFAULT NULL,
	`IS_HIDDEN` TINYINT NULL DEFAULT NULL,
	`TITLE` VARCHAR(255) NULL DEFAULT NULL,
    `CONTENT` VARCHAR(255) NULL DEFAULT NULL,
    `IS_NOTICE` TINYINT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `FILE_ATTACH` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`UPDATE_ID` BIGINT NULL DEFAULT NULL,
	`IS_DELETE` TINYINT NULL DEFAULT NULL,
    `FILE_TYPE` VARCHAR(255) NULL DEFAULT NULL,
    `FILE_NAME` VARCHAR(255) NULL DEFAULT NULL,
    `FILE_PATH` VARCHAR(2048) NULL DEFAULT NULL,
    `THUMNAIL_PATH` VARCHAR(2048) NULL DEFAULT NULL,
    `FILE_SIZE` INT NULL DEFAULT NULL,
    `FILE_EXTENSION` VARCHAR(255) NULL DEFAULT NULL,
    `CONTENT_TYPE` VARCHAR(255) NULL DEFAULT NULL,
    `ENTITY_TYPE` VARCHAR(255) NULL DEFAULT NULL,
    `ENTITY_ID` BIGINT NULL DEFAULT NULL,
    `IS_FIRST_IMAGE` TINYINT NULL DEFAULT NULL,
    `IS_IMAGE` TINYINT NULL DEFAULT NULL,
    `IMAGE_BASE64` LONGTEXT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `COMMENT` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`UPDATE_ID` BIGINT NULL DEFAULT NULL,
	`IS_DELETE` TINYINT NULL DEFAULT NULL,
	`IS_HIDDEN` TINYINT NULL DEFAULT NULL,
    `CONTENT` VARCHAR(255) NULL DEFAULT NULL,
	`ENTITY_TYPE` VARCHAR(255) NULL DEFAULT NULL,
    `ENTITY_ID` BIGINT NULL DEFAULT NULL,
    `IS_NOTICE` TINYINT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `MEMBER` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`UPDATE_ID` BIGINT NULL DEFAULT NULL,
	`IS_DELETE` TINYINT NULL DEFAULT NULL,
    `LOGIN_TOKEN` VARCHAR(255) NULL DEFAULT NULL,
    `SNS_PROVIDER` VARCHAR(50) NULL DEFAULT NULL,
    `SNS_PROVIDER_ID` VARCHAR(255) NULL DEFAULT NULL,
    `LOGIN_ID` VARCHAR(255) NULL DEFAULT NULL,
    `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
    `PASSWORD` VARCHAR(2048) NULL DEFAULT NULL,
    `PASSWORD_EXPIRED_DATE` TIMESTAMP NULL DEFAULT NULL,
    `NAME` VARCHAR(255) NULL DEFAULT NULL,
	`AUTH_NAME` VARCHAR(255) NULL DEFAULT NULL,
    `PROFILE_IMAGE_PATH` VARCHAR(2048) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `ROOM` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`TITLE` VARCHAR(255) NULL DEFAULT NULL,
	`ROOM_TYPE` VARCHAR(20) NULL DEFAULT NULL,
	`CREATE_ID` BIGINT NULL DEFAULT NULL,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `CHAT_MESSAGE` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`MESSAGE` VARCHAR(2048) NULL DEFAULT NULL,
	`MEMBER_TYPE` VARCHAR(20) NULL DEFAULT NULL,
	`ROOM_ID` BIGINT NULL DEFAULT NULL,
	`MEMBER_ID` BIGINT NULL DEFAULT NULL,
	`IS_NO_MEMBER` TINYINT NULL DEFAULT NULL,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `READ_MESSAGE` (
	`ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`MESSAGE_ID` BIGINT NULL DEFAULT NULL,
	`MEMBER_ID` BIGINT NULL DEFAULT NULL,
	`IS_READ` TINYINT NULL DEFAULT NULL,
	`CREATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);