CREATE TABLE IF NOT EXISTS MEMBER_TEST (
  ID int NOT NULL AUTO_INCREMENT,
  EMAIL varchar(255) DEFAULT NULL,
  PASSWORD varchar(100) DEFAULT NULL,
  NAME varchar(100) DEFAULT NULL,
  REGDATE datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMAIL (EMAIL)
);

