INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '공지사항');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '일반 게시판');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '익명 게시판');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '동호회');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '상조회');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '카페');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '자유 게시판');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '중고나라 게시판');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '전사 게시판');
INSERT INTO BOARD(CREATE_DATE, UPDATE_DATE, CREATE_ID, UPDATE_ID, IS_DELETE, IS_HIDDEN, TITLE) VALUES(NOW(), NOW(), NULL, NULL, 0, 0, '부서 게시판');

-- message insert
INSERT INTO APP_MESSAGE(CODE, LANG, MESSAGE) VALUES('server.welcome', 'ko', '서버입니다(DB)');
INSERT INTO APP_MESSAGE(CODE, LANG, MESSAGE) VALUES('client.welcome', 'ko', '클라이언트입니다(DB)');
INSERT INTO APP_MESSAGE(CODE, LANG, MESSAGE) VALUES('server.welcome', 'en', 'SERVER_WELCOME(DB)');
INSERT INTO APP_MESSAGE(CODE, LANG, MESSAGE) VALUES('client.welcome', 'en', 'CLIENT_WELCOME(DB)');